services:
  node1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: raft-node-1
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node1
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080
    ports:
      - "8081:8080"

  node2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: raft-node-2
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node2
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080
    ports:
      - "8082:8080"

  node3:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: raft-node-3
    environment:
      - SERVER_PORT=8080
      - NODE_ID=node3
      - CLUSTER_NODES=http://node1:8080,http://node2:8080,http://node3:8080
    ports:
      - "8083:8080"
